<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIN_TextInput__control</name>
   <tag></tag>
   <elementGuidId>74fb1b11-516a-4549-bba9-ba713e87ca62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.TextInput__input.TextInput__input_r4 > span.TextInput__box > input.TextInput__control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;SusaninReact&quot;]/div[@class=&quot;page page_type_history-by-vin&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ProAutoLandingDesktop&quot;]/div[@class=&quot;ProAutoLandingDesktop__top&quot;]/div[@class=&quot;ProAutoLandingDesktop__vinCheckSnippetTop&quot;]/div[@class=&quot;VinCheckSnippetDesktop&quot;]/div[@class=&quot;VinCheckSnippetDesktop__input&quot;]/div[@class=&quot;VinCheckInput&quot;]/span[@class=&quot;ControlGroup ControlGroup_responsive_no ControlGroup_width_full&quot;]/label[@class=&quot;TextInput TextInput_size_xxl TextInput_hovered TextInput_has-clear TextInput_has-placeholder TextInput_placeholderShowWithValue TextInput_color_whiteNoBordersBg&quot;]/div[@class=&quot;TextInput__input TextInput__input_r4&quot;]/span[@class=&quot;TextInput__box&quot;]/input[@class=&quot;TextInput__control&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div[3]/div/div/div/div[2]/div/span/label/div/span/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label/div/span/input</value>
   </webElementXpaths>
</WebElementEntity>
